#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

# an attempt to set colors
#
# black blue brown cyan dark-gray green red white yellow magneta
# light-cyan light-blue light-gray light-magenta light-red light-green
#
#set menu_color_normal=light-red/dark-gray
#set menu_color_highlight=dark-gray/light-red
#set color_normal=light-red/dark-gray
set menu_color_normal=brown/black
set menu_color_highlight=black/brown
set color_normal=brown/black
